<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkHoursTracker.Infrastructure\WorkHoursTracker.Infrastructure.csproj" />
  </ItemGroup>
</Project>
